
Why Ansible is popular?

  - Easy to learn
  - Written in Python
  - no need to learn a new language (Playbooks are written in YAML)

Pre-requisites:
  - ssh connectivity (Passwordless)
  - Python (on Both Master and nodes)


## Ansible command line
ansible --> Ansible AdHoc Commands
ansible-playbook --> Ansible Playbooks
ansible-galaxy --> Ansible roles

## Ansible terminology
    AdHoc Commands
    Tasks
    Play
    Playbooks
    Roles
    

================================
PasswordLess Authentication
================================
## Create a System Account
adduser ansible
sudo usermod -aG sudo ansible
visudo => /etc/sudoers
%sudo (ALL)=(ALL) NOPASSWD:ALL

## Create passwordless Authentication
su - ansible
ssh-keygen -t rsa
ssh ansible@178.128.12.237 mkdir -p .ssh
cat .ssh/id_rsa.pub | ssh ansible@178.128.12.237 'cat  >> .ssh/authorized_keys'

##Alternatively you can use below command as well to copy ssh key:

ssh-copy-id -i .ssh/id_rsa.pub ansible@<<ipaddress>>

Note: You might have to edit /etc/ssh/sshd_config file on all nodes for ssh to be enabled.

Make sure the following line exists and it is uncommented

PasswordAuthentication yes

*****************
Restart service
*****************
sudo service sshd restart
sudo systemctl restart sshd

=======================
Installation
=======================
##Installation
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get install -y ansible

##Validation
ansible --version

=======================
ansible.cfg => /etc/ansible/ansible.cfg
=======================
## Inventory File
##Default location: /etc/ansible/hosts
##use -i if you want to provide any other file.

[ubuntu-nodes]
slmaster ansible_host=xx.xx.xx.xx
slnode ansible_host=xx.xx.xx.xx

[rhel-nodes]
slmaster ansible_host=xx.xx.xx.xx
slnode ansible_host=xx.xx.xx.xx

[local]
slmaster ansible_host=xx.xx.xx.xx

[Alllinuxnodes:members]
ubuntu-nodes
rhel-nodes


Ex: A collection of hosts belonging to the 'webservers' group

## [webservers]
## alpha.example.org
## beta.example.org
## 192.168.1.100
## 192.168.1.110

Reference: https://docs.ansible.com/ansible/2.3/intro_inventory.html

=======================
Ad-Hoc Commands
=======================

Ansible AdHoc Commands:

# Check node health
ansible all -m ping

# List all Ansible nodes
ansible --list-hosts all

# Run shell commands on nodes
ansible nodes -m shell -a 'fdisk -l'

# Run Shell commands on nodes with elevated privileges
ansible nodes -m shell -a 'fdisk -l' --become

# Upload a file to nodes
ansible nodes -m copy -a 'src=test.conf dest=/tmptest.conf owner=root mode=0644' --become -K

# Install a Package:
ansible nodes -m apt -a 'name=nginx state=latest' --become

# Run the following, if needed:
ansible nodes -m shell -a 'apt update' --become

# Uninstall a Package:
ansible nodes -m apt -a 'name=nginx state=absent purge=yes' --become

# Start a Service
ansible nodes -m service -a 'name=nginx state=started enabled=yes' --become

# Stop a Service
ansible nodes -m service -a 'name=nginx state=stopped' --become

## Suppress Deprecation Warning
vi /etc/ansible/ansible.cfg
Go to Line ~180
Change
deprecation_warnings = True
to
deprecation_warnings = False


=======================
Playbooks
=======================

# ping.yml
---
- hosts: all
  remote_user: ansible
  become: yes
  tasks:
    - name: Ping all servers in my infrastructure
      action: ping


## Basic playbook
---
- hosts: nodes
  become: yes
  tasks:
    - name: install screen
      yum:
        name: screen
        state: latest


## Variables in Ansible playbook
---
- hosts: '{{ myhosts }}'
  become: yes
  tasks:
    - name: install specified package on above mentioned servers
      yum:
        name: '{{ pkg }}'
        state: latest

=======================
Roles
=======================

Default role locations:
- /home/ansible/.ansible/roles
- /etc/ansible/roles
- /usr/share/ansible/roles

Install the role:
  - ansible-galaxy install username.role_name
  - ansible-galaxy install nginxinc.nginx


## nginx-role
---
- name: nginx
  hosts: nodes
  become: yes
  tasks:
    - name: Install NGINX on nodes
      include_role:
        name: nginxinc.nginx



References:
https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#about-playbooks
https://github.com/ansible/awx

